# Generated by Django 5.0.1 on 2025-11-16 13:56

import core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('access_method', models.CharField(choices=[('view', 'View'), ('download', 'Download')], default='view', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('expired', 'File Expired'), ('view_limit', 'View Limit Reached'), ('wrong_password', 'Wrong Password'), ('deleted', 'File Deleted'), ('inactive', 'File Inactive')], max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_method', models.CharField(choices=[('email', 'Email'), ('link', 'Link'), ('qr', 'QR Code')], default='link', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('is_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Share',
                'verbose_name_plural': 'File Shares',
                'db_table': 'file_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA256 hash', max_length=64)),
                ('content_type', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('access_token', models.CharField(db_index=True, default=core.utils.generate_secure_token, max_length=64, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_hours', models.IntegerField(default=24)),
                ('expires_at', models.DateTimeField()),
                ('max_views', models.IntegerField(default=10)),
                ('current_views', models.IntegerField(default=0)),
                ('disable_download', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
